import Seo from "../common/Seo.jsx";
import PageHeader from "../layout/PageHeader.jsx";
import BlogCard from "./BlogCard.jsx";
import BlogFilters from "./BlogFilters.jsx";

export default function BlogList({ posts, selectedTag, setSelectedTag }) {
  const filteredPosts = selectedTag === "All" 
    ? posts 
    : posts.filter(post => post.tags?.includes(selectedTag));

  return (
    <>
      <Seo
        title="AI Startup Idea Blog | Startup Idea Advisor"
        description="Insights, playbooks, and weekly ideas generated by our AI advisor to inspire your next venture."
        path="/blog"
      />

      {/* Hero Section */}
      <PageHeader
        title="Ideas & Playbooks"
        subscript="Weekly insights and curated ideas from Startup Idea Advisor"
        description="Subscribe to stay ahead of the curve."
        className="text-center mb-16"
      />

      {/* Filter Section */}
      <BlogFilters 
        selectedTag={selectedTag} 
        setSelectedTag={setSelectedTag} 
        posts={posts} 
      />

      {/* Blog Posts */}
      <div className="max-w-7xl mx-auto px-6">
        {filteredPosts.length > 0 ? (
          <div className="grid gap-6 md:grid-cols-2 auto-rows-fr">
            {filteredPosts.map((post, index) => (
              <BlogCard key={post.slug} post={post} index={index} />
            ))}
          </div>
        ) : (
          <div className="text-center py-12">
            <p style={{ color: "var(--mkt-paragraph)" }}>No articles found in this category.</p>
          </div>
        )}
      </div>
    </>
  );
}

