import { Link } from "react-router-dom";
import { useReports } from "../../context/ReportsContext.jsx";
import { useQuery } from "../../hooks/useQuery.js";
import { useDarkMode } from "../../hooks/useDarkMode.js";
import { useProfileReportState } from "../../hooks/profile/useProfileReportState.js";
import { getSectionTheme } from "../../utils/formatters/profileTheme.js";
import { ProfileSuccessBanner } from "../../components/profile/ProfileSuccessBanner.jsx";
import { ProfileSection } from "../../components/profile/ProfileSection.jsx";
import Seo from "../../components/common/Seo.jsx";
import CacheIndicator from "../../components/common/CacheIndicator.jsx";

// Sample profile analysis data (JSON format)
const SAMPLE_PROFILE_ANALYSIS = `---PROFILE_ANALYSIS_START---
{
 "core_motivations": "You're looking to generate extra income while maintaining flexibility. Your interest in technology and automation suggests you value efficiency and scalable solutions.",
 "operating_constraints": "- Time: Limited to ≤ 5 hours/week, requiring solutions that can be built and managed part-time\n- Budget: Working with a lean budget, prioritizing cost-effective tools and strategies\n- Work style: Prefer structured, systematic approaches that allow for incremental progress",
 "strengths_and_capabilities": "- Technical skills enable rapid prototyping and iteration\n- Understanding of product development and user needs\n- Ability to work independently and systematically",
 "strategic_considerations": "- Focus on ideas that can be validated quickly with minimal investment\n- Have clear monetization paths\n- Leverage your existing skills and knowledge\n- Can scale without requiring full-time commitment initially",
 "viability_red_flags": "- Limited time commitment may restrict growth potential\n- Lean budget requires careful cost management\n- Part-time approach may limit customer acquisition speed",
 "pathway_recommendation": "Start with a low-cost digital product or SaaS tool that leverages your technical skills. Validate with a minimal viable product (MVP) within your time constraints, then gradually scale based on market response."
}
---PROFILE_ANALYSIS_END---`;

export default function ProfileReport() {
  const { reports, loadRunById, loading: reportsLoading, isCached } = useReports();
  const query = useQuery();
  const runId = query.get("id");
  const isSample = query.get("sample") === "true";
  const isDark = useDarkMode();

  // Use centralized hook for all profile report state and logic
  const {
    openSections,
    isLoading,
    effectiveProfileAnalysis,
    sections,
    toggleSection
  } = useProfileReportState({
    reports,
    loadRunById,
    runId,
    isSample,
    SAMPLE_PROFILE_ANALYSIS
  });

 return (
 <section className="grid gap-6">
 <Seo
 title="Profile Analysis Report | Startup Idea Advisor"
 description="Detailed analysis of your entrepreneurial profile generated by our AI advisor."
 path="/dashboard/profile"
 />
 
 {isSample && (
 <div className="rounded-xl border border-default shadow-sm bg-surface p-6 md:p-7 text-center">
 <p className="text-base text-primary leading-relaxed">
 📋 Sample Profile Analysis — This is a demonstration of what you'll receive
 </p>
 </div>
 )}
 
 <article className="rounded-xl border border-default shadow-sm bg-surface p-6 md:p-7 relative">
 <div className="absolute -top-10 -left-10 w-[260px] h-[260px] rounded-full bg-surface opacity-[0.09] blur-2xl pointer-events-none"></div>
 <div className="relative z-10">
 {isSample && (
 <div className="mb-6">
 <Link 
 to="/product" 
 className="inline-flex items-center gap-2 text-sm font-medium text-accent hover:text-accent transition-colors"
 >
 <span aria-hidden="true">←</span> Back to product
 </Link>
 </div>
 )}
 
 {!isSample && reports?.personalized_recommendations && reports.personalized_recommendations.trim() && (
 <ProfileSuccessBanner runId={runId} />
 )}
 
 {isLoading || reportsLoading ? (
 <div className="rounded-xl border border-default shadow-sm bg-surface p-6 md:p-7 text-center">
 <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-accent mx-auto mb-4"></div>
 <p className="text-base text-secondary leading-relaxed">Loading profile analysis...</p>
 </div>
 ) : !effectiveProfileAnalysis ? (
 <div className="rounded-xl border border-default shadow-sm bg-surface p-6 md:p-7">
 <p className="text-base text-primary leading-relaxed mb-4">No profile analysis available. Please run a new analysis first.</p>
 {runId && (
 <p className="text-sm text-secondary">
 Run ID: {runId}
 </p>
 )}
 </div>
 ) : sections.length === 0 ? (
 <div className="rounded-xl border border-default shadow-sm bg-surface p-6 md:p-7">
 <p className="text-base text-primary leading-relaxed mb-4">Could not parse profile analysis JSON. Expected format with delimiters:</p>
 <pre className="text-sm text-secondary bg-app p-3 rounded overflow-auto max-h-64 font-mono">
 ---PROFILE_ANALYSIS_START---{'\n'}
 {'{'}{'\n'}
 {' "core_motivations": "...",'}{'\n'}
 {' "operating_constraints": "...",'}{'\n'}
 {' "strengths_and_capabilities": "...",'}{'\n'}
 {' "strategic_considerations": "...",'}{'\n'}
 {' "viability_red_flags": "...",'}{'\n'}
 {' "pathway_recommendation": "..."'}{'\n'}
 {'}'}{'\n'}
 ---PROFILE_ANALYSIS_END---
 </pre>
 <p className="text-sm mt-4 text-secondary">
 Raw content length: {effectiveProfileAnalysis?.length || 0} characters
 </p>
 </div>
 ) : (
 <div className="grid gap-4">
 {sections.map((section, index) => {
 const theme = getSectionTheme(section.title, index, isDark);
 const sectionNumber = index + 1;
 const isSectionOpen = openSections.has(index);
 
 return (
 <ProfileSection
 key={index}
 section={section}
 theme={theme}
 sectionNumber={sectionNumber}
 isOpen={isSectionOpen}
 onToggle={() => toggleSection(index)}
 />
 );
 })}
 </div>
 )}
 </div>
 </article>
 <CacheIndicator isCached={isCached} />
 </section>
 );
}
